### ISSUE TITLE
[bug] running the script for the first time fails

### ISSUE THREAD

**Issue by GresilleSiffle** [NatNgs/Tournesol-Stats#1]
### how to reproduce

After having cloned the repository in a new folder and installed the dependencies:
- run the script `src/main.py <path_to_dataset> <user>`

### current behaviour

```
Loading channels data...
Traceback (most recent call last):
  File "Tournesol-Stats/src/main.py", line 23, in <module>
    videos = data_fetcher.do_fetch(input_dir, target_user) # {vid: Video, ...}
  File "Tournesol-Stats/src/scripts/data_fetcher.py", line 59, in do_fetch
    CHANNELS = load_channels_data() # {cid: Channel}
  File " Tournesol-Stats/src/model/channel.py", line 14, in load_channels_data
    file = open(FILE_LOCATION, 'r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'data/cache/channel_info.tsv'
```

### expected

The required folders like `data/cache`, `data/output` and the required files should be created if they don't exist.

```python
# Example for the folders creation.
from pathlib import Path

Path('data/cache').mkdir(parents=True, exist_ok=True)
```

See: https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir

**Comment by NatNgs** [comment]
Should be fixed, and fix merged onto main branch
